// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXMxx65mbyGrC8dRSPPqxCp2htW6YSuNU',
    appId: '1:217245752751:web:8ead797ee561af9f80a35a',
    messagingSenderId: '217245752751',
    projectId: 'restaurant-app-8e7ba',
    authDomain: 'restaurant-app-8e7ba.firebaseapp.com',
    storageBucket: 'restaurant-app-8e7ba.firebasestorage.app',
    measurementId: 'G-RVPW16H2FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByx39I1fq0sfTHj9lVDD1xF_otGUl8B4w',
    appId: '1:217245752751:android:529e0ac59a14c4ad80a35a',
    messagingSenderId: '217245752751',
    projectId: 'restaurant-app-8e7ba',
    storageBucket: 'restaurant-app-8e7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0vwVkgmlsY5SJvljl81Mpnk4cQrexgPg',
    appId: '1:217245752751:ios:2ff27a750e2097c580a35a',
    messagingSenderId: '217245752751',
    projectId: 'restaurant-app-8e7ba',
    storageBucket: 'restaurant-app-8e7ba.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0vwVkgmlsY5SJvljl81Mpnk4cQrexgPg',
    appId: '1:217245752751:ios:2ff27a750e2097c580a35a',
    messagingSenderId: '217245752751',
    projectId: 'restaurant-app-8e7ba',
    storageBucket: 'restaurant-app-8e7ba.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXMxx65mbyGrC8dRSPPqxCp2htW6YSuNU',
    appId: '1:217245752751:web:06937572789b0d4b80a35a',
    messagingSenderId: '217245752751',
    projectId: 'restaurant-app-8e7ba',
    authDomain: 'restaurant-app-8e7ba.firebaseapp.com',
    storageBucket: 'restaurant-app-8e7ba.firebasestorage.app',
    measurementId: 'G-GVP4T11FZY',
  );
}
